// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jubohwwznfgenfiwitmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp1Ym9od3d6bmZnZW5maXdpdG1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNjkyNDAsImV4cCI6MjA1NTg0NTI0MH0.F3X0s1pQtD80iZ37lGMy1nBqiA5EWyXBbNlRGFay5ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);